// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about_me from "./routes/about-me.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $services from "./routes/services.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $mobile_header from "./islands/mobile-header.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about-me.tsx": $about_me,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/services.tsx": $services,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/mobile-header.tsx": $mobile_header,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
